//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTutorial.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int EmployeeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Forname { get; set; }
        public string Surname { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> AddressId { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site> Sites { get; set; }
        public virtual Address Address { get; set; }
    }
}
